version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "logistics_system"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -padmin"]
      interval: 5s
      retries: 10
      timeout: 5s

  web:
    build: .
    command: >
      sh -c "python backend_api/manage.py makemigrations backend&&
             python backend_api/manage.py migrate &&
             python backend_api/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend_api:/app/backend_api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "8080:80"
    depends_on:
      - db
